name: Docker Image CI

on:
  push:
    branches: [ "main" ]
env:
  DISTRO: bookworm
  PG_IMAGE: postgresql-debugger
  INITDB: ./initdb
jobs:
  build-and-push:
    strategy:
      matrix:
        version: [14, 15, 16]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        build-args: |
              VERSION=${{ matrix.version }}
              DISTRO=${{ env.DISTRO }}
              INITDB=${{ env.INITDB }}
        file: Dockerfile
        push: true
        tags: | 
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PG_IMAGE }}:${{ matrix.version }}-${{ env.DISTRO }}
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PG_IMAGE }}:${{ matrix.version }}
      
